import { Book } from './book.model';
import { Genre } from './genre.enum';

export const BOOKS: Book[] = [
  {
    id: 1,
    title: 'Clean Code',
    author: 'Robert C. Martin',
    genre: Genre.FICTION,
    year: 2008,
    pages: 464,
    rating: 4.7,
    available: true,
    description: 'A handbook of agile software craftsmanship',
  },
  {
    id: 2,
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    genre: Genre.FANTASY,
    year: 1937,
    pages: 310,
    rating: 4.8,
    available: false,
  },
  {
    id: 3,
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    genre: Genre.FANTASY,
    year: 1954,
    pages: 1178,
    rating: 4.9,
    available: true,
    description: 'An epic high-fantasy novel set in Middle-earth',
  },
  {
    id: 4,
    title: 'Harry Potter and the Sorcerer’s Stone',
    author: 'J.K. Rowling',
    genre: Genre.FANTASY,
    year: 1997,
    pages: 309,
    rating: 4.8,
    available: true,
    description: 'A young wizard’s journey begins at Hogwarts',
  },
  {
    id: 5,
    title: 'The Pragmatic Programmer',
    author: 'Andrew Hunt, David Thomas',
    genre: Genre.FICTION,
    year: 1999,
    pages: 352,
    rating: 4.6,
    available: true,
    description: 'Practical advice for modern software developers',
  },
  {
    id: 6,
    title: 'Game of Thrones',
    author: 'George R.R. Martin',
    genre: Genre.FANTASY,
    year: 1996,
    pages: 694,
    rating: 4.7,
    available: false,
    description: 'Noble families vie for control of the Iron Throne',
  },
  {
    id: 7,
    title: 'Refactoring',
    author: 'Martin Fowler',
    genre: Genre.FICTION,
    year: 1999,
    pages: 448,
    rating: 4.5,
    available: true,
    description: 'Improving the design of existing code',
  },
  {
    id: 8,
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    genre: Genre.FANTASY,
    year: 2007,
    pages: 662,
    rating: 4.7,
    available: true,
    description: 'The story of a legendary magician told in his own voice',
  },
];
